version: 1.0.{build}

skip_tags: true

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

artifacts:
  - path: ImageSplitter\bin\$(configuration)\ImageSplitter.exe
    name: ImageSplitter.exe

deploy:
  release: ImageSplitter-v$(appveyor_build_version)
  description: 'Image Splitter'
  provider: GitHub
  auth_token:
    secure: iIQYZTIjnJwRMu4NGFO9iDWVxiULK/6RfSWY6R9Z8W7daJPdGQGMBqblEcpYa9xZ
  artifact: ImageSplitter.exe
  on:
    branch: master
